// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DebtorPaymentSplit } from "./DebtorPaymentSplit";

export type DebtorPayment = { id: number, loan_id: number, amount_cents: number, paid_at: number, notes: string | null, splits: Array<DebtorPaymentSplit>, created_at: number, created_by: number | null, };
