// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LoanLender = { lender_id: number, lender_name: string, amount_lent_cents: number, };
