// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AuditEntry = { id: number, at: number, user_id: number | null, user_name: string | null, action: string, entity_type: string, entity_id: number | null, payload: string | null, };
