// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { User } from "./User";

export type AuthStatus = { needs_setup: boolean, current_user: User | null, };
