// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LenderPayout = { id: number, lender_id: number, lender_name: string, currency_code: string, amount_cents: number, paid_at: number, notes: string | null, created_at: number, created_by: number | null, };
