// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LenderBalance = { lender_id: number, lender_name: string, currency_code: string, received_cents: number, paid_out_cents: number, outstanding_cents: number, };
