// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LoanLender } from "./LoanLender";
import type { LoanStatus } from "./LoanStatus";

export type Loan = { id: number, reference: string | null, debtor_id: number, debtor_name: string, currency_code: string, principal_cents: number, interest_cents: number, issued_at: number, status: LoanStatus, notes: string | null, lenders: Array<LoanLender>, created_at: number, created_by: number | null, };
