// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Party = { id: number, name: string, external_ref: string | null, notes: string | null, created_at: number, created_by: number | null, };
